name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
        name: prod
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            main:
              - 'docker/**'
      -
        name: Checkout
        if: steps.filter.outputs.main == 'true'
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        if: steps.filter.outputs.main == 'true'
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        if: steps.filter.outputs.main == 'true'
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Registry
        if: steps.filter.outputs.main == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      -
        name: Build & Push openvpn container
        if: steps.filter.outputs.main == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./docker/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/atlantishq/openvpn-atlantis:latest"
